config/routes.rb
require "sidekiq/web"

Liveinspired::Application.routes.draw do
  root to: "home#index"

  mount Sidekiq::Web => "/sidekiq"
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"

  devise_for :users

  resources :channels do
    member do
      get :list_subscribers
      get :messages_report
    end

    resources :messages do
      member do
        post :broadcast
        post :move_up
        post :move_down
        get :responses
      end
      collection do
        get :select_import
        post :import
      end

      resources :response_actions do
        collection do
          get :select_import
          post :import
        end
      end
    end
  end

  post "channels/:channel_id/add_subscriber/:id" => "channels#add_subscriber", :as => "channel_add_subscriber"
  post "channels/:channel_id/remove_subscriber/:id" => "channels#remove_subscriber", :as => "channel_remove_subscriber"

  resources :channel_groups, except: [:index] do
    member do
      get  :messages_report
      get  :clone
      post :copy
      get  :messages_report
    end
  end

  post "channel_groups/:channel_group_id/remove_channel/:id" => "channel_groups#remove_channel", :as => "channel_group_remove_channel"

  resources :users
  resources :subscribers

  resources :subscriber_activities, except: %i(new create destroy)

  resources :downloads, only: [:index]
  resources :service_identifiers, only: [:index]

  match "subscribe/:channel_group_id" => "home#new_web_subscriber", :via => %i(get post)
  get "thank_you" => "home#sign_up_success"
  post "twilio" => "twilio#callback"

  match "help/user_show", via: :all
  match "help/edit_channel", via: :all
  match "help/edit_message", via: :all
  match "help/index_channels", via: :all
  match "help/edit_response_action", via: :all
  match "help/glossary", via: :all
end

app/models/messages/action_message.rb
# == Schema Information
#
# Table name: messages
#
#  id                           :integer          not null, primary key
#  title                        :text
#  caption                      :text
#  type                         :string(255)
#  channel_id                   :integer
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  content_file_name            :string(255)
#  content_content_type         :string(255)
#  content_file_size            :integer
#  content_updated_at           :datetime
#  seq_no                       :integer
#  next_send_time               :datetime
#  primary                      :boolean
#  reminder_message_text        :text
#  reminder_delay               :integer
#  repeat_reminder_message_text :text
#  repeat_reminder_delay        :integer
#  number_of_repeat_reminders   :integer
#  options                      :text
#  deleted_at                   :datetime
#  schedule                     :text
#  active                       :boolean
#  requires_response            :boolean
#  recurring_schedule           :text
#

class ActionMessage < Message
  def self.user_accessible_message_type?
    true
  end

  def type_abbr
    "Action"
  end

  def internal?
    true
  end

  def send_to_subscribers(subscribers)
    StatsD.increment "message.#{id}.send_to_subscribers", Array(subscribers).length
    action&.execute subscribers: subscribers, channel: channel, message: self
  end
end

app/models/messages/poll_message.rb
# == Schema Information
#
# Table name: messages
#
#  id                           :integer          not null, primary key
#  title                        :text
#  caption                      :text
#  type                         :string(255)
#  channel_id                   :integer
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  content_file_name            :string(255)
#  content_content_type         :string(255)
#  content_file_size            :integer
#  content_updated_at           :datetime
#  seq_no                       :integer
#  next_send_time               :datetime
#  primary                      :boolean
#  reminder_message_text        :text
#  reminder_delay               :integer
#  repeat_reminder_message_text :text
#  repeat_reminder_delay        :integer
#  number_of_repeat_reminders   :integer
#  options                      :text
#  deleted_at                   :datetime
#  schedule                     :text
#  active                       :boolean
#  requires_response            :boolean
#  recurring_schedule           :text
#

class PollMessage < Message
  def self.user_accessible_message_type?
    true
  end

  def type_abbr
    "Poll"
  end

  def requires_user_response?
    true
  end

  def check_subscriber_response(subscriber_response_content_text)
    false
  end
end

app/models/messages/response_message.rb
# == Schema Information
#
# Table name: messages
#
#  id                           :integer          not null, primary key
#  title                        :text
#  caption                      :text
#  type                         :string(255)
#  channel_id                   :integer
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  content_file_name            :string(255)
#  content_content_type         :string(255)
#  content_file_size            :integer
#  content_updated_at           :datetime
#  seq_no                       :integer
#  next_send_time               :datetime
#  primary                      :boolean
#  reminder_message_text        :text
#  reminder_delay               :integer
#  repeat_reminder_message_text :text
#  repeat_reminder_delay        :integer
#  number_of_repeat_reminders   :integer
#  options                      :text
#  deleted_at                   :datetime
#  schedule                     :text
#  active                       :boolean
#  requires_response            :boolean
#  recurring_schedule           :text
#

class ResponseMessage < Message
  def self.user_accessible_message_type?
    true
  end

  def type_abbr
    "Response"
  end

  def requires_user_response?
    true
  end

  def has_action_on_user_response?
    true
  end

  def process_subscriber_response(s_response)
    response_action = check_subscriber_response(s_response.content_text)
    if response_action
      response_action.action&.execute subscribers: [s_response.subscriber], from_channel: channel
    end
    true
  end

  def check_subscriber_response(subscriber_response_content_text)
    response_actions.find_each do |response_action|
      next unless subscriber_response_content_text =~ /#{response_action.response_text}/
      return response_action
    end
  end
end

app/models/messages/simple_message.rb
# == Schema Information
#
# Table name: messages
#
#  id                           :integer          not null, primary key
#  title                        :text
#  caption                      :text
#  type                         :string(255)
#  channel_id                   :integer
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  content_file_name            :string(255)
#  content_content_type         :string(255)
#  content_file_size            :integer
#  content_updated_at           :datetime
#  seq_no                       :integer
#  next_send_time               :datetime
#  primary                      :boolean
#  reminder_message_text        :text
#  reminder_delay               :integer
#  repeat_reminder_message_text :text
#  repeat_reminder_delay        :integer
#  number_of_repeat_reminders   :integer
#  options                      :text
#  deleted_at                   :datetime
#  schedule                     :text
#  active                       :boolean
#  requires_response            :boolean
#  recurring_schedule           :text
#

class SimpleMessage < Message
  def self.user_accessible_message_type?
    true
  end

  def type_abbr
    "Simple"
  end
end

app/models/messages/tag_message.rb
# == Schema Information
#
# Table name: messages
#
#  id                           :integer          not null, primary key
#  title                        :text
#  caption                      :text
#  type                         :string(255)
#  channel_id                   :integer
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  content_file_name            :string(255)
#  content_content_type         :string(255)
#  content_file_size            :integer
#  content_updated_at           :datetime
#  seq_no                       :integer
#  next_send_time               :datetime
#  primary                      :boolean
#  reminder_message_text        :text
#  reminder_delay               :integer
#  repeat_reminder_message_text :text
#  repeat_reminder_delay        :integer
#  number_of_repeat_reminders   :integer
#  options                      :text
#  deleted_at                   :datetime
#  schedule                     :text
#  active                       :boolean
#  requires_response            :boolean
#  recurring_schedule           :text
#

class TagMessage < Message
  def self.user_accessible_message_type?
    true
  end

  def type_abbr
    "Tag"
  end

  def caption_for(subscriber)
    return false if !(subscriber.has_custom_attributes? && message_text?(subscriber))

    keys = matching_message_options(subscriber)
    candidate_msgs = message_options.select { |mo| keys.include?(mo[:key]) }.map(&:value)
    sent_msgs = DeliveryNotice
      .where(
        subscriber_id: subscriber.id,
        caption: candidate_msgs,
      )
      .map(&:caption)
    remaining_msgs = candidate_msgs - sent_msgs

    remaining_msgs.length > 0 ? remaining_msgs.sample : candidate_msgs.sample
  end

  def message_text?(subscriber)
    matching_message_options(subscriber).length > 0
  end

  def matching_message_options(subscriber)
    common_keys = []
    subscriber.custom_attributes.keys.each do |sk|
      common_keys.push message_option_keys.select { |mk| mk.downcase == sk.downcase }
    end
    common_keys
  end

  def message_option_keys
    @message_option_keys ||= message_options.all.map(&:key)
  end
end

app/controllers/messages_controller.rb
require "will_paginate/array"
# test
class MessagesController < ApplicationController
  before_action :load_channel
  before_action :load_to_channel_options, only: %i(new edit show create update)

  def index
    @messages = @channel.messages
    respond_to do |format|
      format.html
      format.json { render json: @messages }
      format.csv { send_data Message.where(channel_id: @channel.id).my_csv }
      format.xls { send_data Message.where(channel_id: @channel.id).my_csv(col_sep: "\t") }
    end
  end

  def show
    @message = @channel.messages.find(params[:id])
    @action = @message.action

    if @message.requires_user_response?
      @grouped_responses = @message.grouped_responses || []
    end

    @channel_group_id_map = {}
    current_user.channel_groups.each do |channel_group|
      @channel_group_id_map[channel_group.id] = channel_group.name
    end

    respond_to do |format|
      format.html
      format.json { render json: @message }
    end
  end

  def new
    @message = @channel.messages.new
    @action = @message.build_action
    3.times { @message.message_options.build }

    @channel_group_id_map = {}
    current_user.channel_groups.each do |channel_group|
      @channel_group_id_map[channel_group.id] = channel_group.name
    end

    @channels = current_user.channels

    respond_to do |format|
      format.html
      format.json { render json: @message }
    end
  end

  def edit
    @message = @channel.messages.find(params[:id])
    @action = @message.action
    @channels = current_user.channels
  end

  def create
    @message = MessageFactoryService
      .new(message_params, params, message: nil, channel: @channel)
      .message
    @channels = current_user.channels

    respond_to do |format|
      if @message.save
        format.html { redirect_to [@channel, @message], notice: "Message was successfully created." }
        format.json { render json: @message, status: :created, location: [@channel, @message] }
      else
        Rails.logger.info "**#{@message.errors.inspect}"
        format.html { render action: :new, error: @message.errors.messages }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @message = @channel.messages.find(params[:id])
    @message = MessageFactoryService
      .new(message_params, params, message: @message, channel: nil)
      .message

    respond_to do |format|
      if @message.save
        format.html { redirect_to [@channel, @message], notice: "Message was successfully updated." }
        format.json { head :no_content }
      else
        Rails.logger.info "**#{@message.errors.inspect}"
        format.html { render action: :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message = @channel.messages.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to channel_url(@channel), page: params[:page_no] }
      format.json { head :no_content }
    end
  end

  def broadcast
    message = @channel.messages.find(params[:id])
    message.broadcast

    respond_to do |format|
      format.html { redirect_to [@channel, @message], notice: "Message was queued for broadcast." }
      format.json { head :no_content }
    end
  end

  def move_up
    message = @channel.messages.find(params[:id])
    message.move_up

    respond_to do |format|
      format.html { redirect_to [@channel, @message] }
      format.json { head :no_content }
    end
  end

  def move_down
    message = @channel.messages.find(params[:id])
    message.move_down

    respond_to do |format|
      format.html { redirect_to [@channel, @message] }
      format.json { head :no_content }
    end
  end

  def responses
    @message = @channel.messages.find(params[:id])
    g_resps = @message.grouped_responses || []
    @grouped_response = g_resps.find { |e| e[:message_content] == params[:with_content] }
    @subscriber_responses = @grouped_response[:subscriber_responses].paginate(
      page: params[:page],
      per_page: 10,
    )
    @response = params[:with_content]
  end

  def select_import
    session[:import_requester] = request.referer
  end

  def import
    file = params[:import][:import_from]
    resp = Message.import(@channel,file)
    notice_message = resp[:message]
    session.delete(:import_requester)
    if resp[:completed]
      redirect_to request.referer, notice: "Messages imported"
    else
      redirect_to request.referer, error: resp[:message]
    end
  end

  private

    def message_params(p = params)
      Array(p.try(:[], "message").try(:[], "message_options_attributes").try(:keys)).each do |key|
        p.try(:[], "message").try(:[], "message_options_attributes").try(:[], key).delete("_destroy")
      end

      if p.try(:[], "message").try(:[], "action_attributes")
        p.try(:[], "message").try(:[], "action_attributes").try(:delete, "id")
      end

      p.require(:message)
        .permit(:title, :caption, :type, :content, :next_send_time,
                :reminder_message_text, :reminder_delay,
                :repeat_reminder_message_text, :repeat_reminder_delay,
                :number_of_repeat_reminders, :action_attributes, :schedule,
                :relative_schedule_type, :relative_schedule_number,
                :relative_schedule_day, :relative_schedule_hour,
                :relative_schedule_minute, :active, :_destroy,
                :message_options_attributes, :recurring_schedule,
                message_options_attributes: %i(key message_id value),
                action_attributes: %i(
                  type as_text to_channel message_to_send resume_from_last_state
                ))
    rescue => e
      binding.pry
      raise e
    end

    def load_channel
      authenticate_user!
      @user = current_user
      @channel = @user.channels.find(params[:channel_id])
      redirect_to root_url, alert: "Access Denied" unless @channel
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, alert: "Access Denied"
    end

    def load_to_channel_options
      @to_channel_options = { in_group: {}, out_group: [] }
      current_user.channels.each do |channel|
        if channel.channel_group_id
          @to_channel_options[:in_group][channel.channel_group_id] ||= []
          @to_channel_options[:in_group][channel.channel_group_id] << [channel.name, channel.id]
        else
          @to_channel_options[:out_group] << [channel.name, channel.id]
        end
      end
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def message_types
    Message.child_classes
  end

  def user_message_types
    Message.child_classes.select { |c| c.user_accessible_message_type? }.map { |c| c.to_s.to_sym }
  end

  def base_message_length(message)
    bml = ENV["TPARTY_SUFFIX_LENGTH"].to_i
    bml += message.channel.suffix.length if message.channel && message.channel.suffix
    bml
  end

  def total_message_length(message)
    tml = base_message_length(message)
    tml += message.caption.length if message.caption
    tml
  end
end

app/views/messages/_form.html.slim
= simple_form_for [@channel, @message], wrapper: :bootstrap_horizontal, html: { class: "form-horizontal" } do |f|
  .row
    .col-md-7
      = f.input :type, label: 'Message Type', collection: user_message_types, include_blank: false, readonly: @message.new_record? ? false : true
      = f.input :caption, label: "Message Text", input_html: { rows: 5 }, hint: "Total message length: #{total_message_length(@message)}"
      = f.input :content

      - if @channel.individual_messages_have_schedule?
        - if @channel.relative_schedule
          = render partial: "shared/relative_schedule", locals: { f: f }
        - else
          = render partial: "shared/absolute_schedule", locals: { f: f, message: @message }

      = render partial: "messages/editor/reminder_section", locals: { f: f }
      = render partial: "messages/editor/message_type_specific_section", locals: { f: f }
      = f.input :active, wrapper: :inline_checkbox_in_horizontal_form, hint: "Making inactive will skip during scheduled send"

  .panel.panel-default style="padding-left: 270px;"
    .panel-body
      => f.button :submit, class: "btn-primary"
      => link_to "Cancel", request.referer, class: "btn btn-default"

- content_for :head_js
  javascript:
    function updateTotalLength() {
      var base_length = #{base_message_length(@message)};
      $('div.message_caption .help-block').text('Total message length:' + ($('#message_caption').val().length + base_length));
    }

    $(document).ready(function () {
      updateTotalLength();
      $('#message_caption').keyup(function (event) {
        updateTotalLength();
      });
    });

app/views/messages/edit.html.slim
- model_class = Message

.page-header.clearfix
  h1.pull-left
    = t ".title", default: [:"helpers.titles.edit", "Edit %{model}"], model: model_class.model_name.human.titleize
  = help_tag help_edit_message_path

= render partial: "form"

app/views/messages/import.html.slim
= @params

app/views/messages/index.html.slim
- model_class = Message

.page-header: h1
  = t ".title", default: model_class.model_name.human.pluralize.titleize

table.table.table-striped
  thead: tr
    th Text
    th Created at
    th= t ".actions", default: t("helpers.actions")
  tbody
    - @messages.find_each do |message|
      tr
        td = link_to message.caption, channel_message_path(@channel, message)
        td = message.created_at
        td
          => link_to t(".edit", default: t("helpers.links.edit")),
                    edit_channel_message_path(@channel, message),
                    class: "btn btn-default btn-xs"
          => link_to t(".destroy", default: t("helpers.links.destroy")),
                    channel_message_path(@channel, message),
                    method: :delete,
                    data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
                    class: "btn btn-xs btn-danger"

=> link_to t(".new", default: t("helpers.links.new")),
          new_channel_message_path(@channel),
          class: "btn btn-primary"

app/views/messages/new.html.slim
- model_class = Message

.page-header.clearfix
  .row
    .col-md-8
      .row
        .col-md-12
          h4.pull-left
            | Create New Message
      .row
        .col-md-12
          p
            = "Channel:  "
            = link_to channel_path(@channel) do
              = " #{@channel.name} "
          - if @channel&.channel_group_id
            p
              = "Group:  "
              = link_to channel_group_path(@channel.channel_group) do
                span.glyphicon.glyphicon-folder-open
                = " #{@channel.channel_group.name}"

    .col-md-4
      = help_tag help_edit_message_path

= render partial: "form"

app/views/messages/responses.html.slim
.page-header
  h2 Subscribers who responded with #{@response[0..50]} for "#{@message.caption[0..50]}"

table#subscriber_response_table.table.table-striped
  thead: tr
    th Subscriber
    th Sent at
  tbody
    - @subscriber_responses.find do |sr|
      tr
        - subscriber = @grouped_response[:subscribers].find { |subs| subs.phone_number == sr.origin }
        td= link_to subscriber.name, subscriber_path(subscriber)
        td= link_to sr.created_at, subscriber_activity_path(sr.id, subscriber_id: subscriber.id)

= will_paginate @subscriber_responses

.form-actions
  = link_to "Back", request.referer, class: "btn btn-default"

app/views/messages/select_import.html.slim
.page-header.clearfix
  h1.pull-left Import messages for #{@channel.name}
  = help_tag help_edit_message_path

= simple_form_for :import, wrapper: :bootstrap_horizontal, url: import_channel_messages_path, html: { class: "form-horizontal", multipart: true } do |f|
  .row
    .col-md-6
      = f.input :import_from, as: :file

  .panel.panel-default style="padding-left: 228px;"
    .panel-body
      = f.button :submit, "Import"

app/views/messages/show.html.slim
- model_class = Message

.page-header: h1 Message

dl.dl-horizontal
  dt: strong Type:
  dd= print_or_dashes @message.type.titlecase
  - if @message.type == 'ActionMessage'
    dt Action:
    dd = @message.action.as_text
  - else
    dt: strong Text:
    dd= print_or_dashes @message.caption
  dt: strong Active:
  dd= print_or_dashes @message.active

  - if @channel.individual_messages_have_schedule?
    - if @channel.relative_schedule
      dt: strong Schedule:
      dd= print_or_dashes @message.schedule
    - else
      dt: strong Next send time:
      dd= print_or_dashes @message.next_send_time

  - if @message.requires_user_response?
    dt: strong Reminder message:
    dd= print_or_dashes @message.reminder_message_text
    dt: strong Send reminder after:
    dd= @message.reminder_delay
    dt: strong Repeat rem message:
    dd= print_or_dashes @message.repeat_reminder_message_text
    dt: strong Send repeat after:
    dd= @message.repeat_reminder_delay
    dt: strong No of repeat reminders:
    dd= @message.number_of_repeat_reminders


div
  - if @message.content.content_type =~ /video/
    = video_tag @message.content.url, controls: true, autobuffer: true, width: "320px", height: "240px"
  - elsif @message.content.content_type =~ /image/
    = image_tag @message.content.url(:thumb)

= render partial: "messages/details/message_type_specific_section"

- if @message.requires_user_response?
  = render partial: "messages/details/message_response_details"

.panel.panel-default.mt-20.mb-20
  .panel-body
    => link_to "Back", channel_path(@channel), class: "btn btn-default"
    => link_to t(".edit", default: t("helpers.links.edit")),
              edit_channel_message_path(@channel, @message),
              class: "btn btn-default"
    => link_to t(".destroy", default: t("helpers.links.destroy")),
              channel_message_path(@channel, @message),
              method: :delete,
              data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
              class: "btn btn-danger"
    => link_to "Subscriber Responses",
              subscriber_activities_path( \
                message_id: @message.id,
                channel_id: @channel.id,
                type: "SubscriberResponse",
              ),
              class: "btn btn-default"