config/routes.rb
require "sidekiq/web"

Liveinspired::Application.routes.draw do
  root to: "home#index"

  mount Sidekiq::Web => "/sidekiq"
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"

  devise_for :users

  resources :channels do
    member do
      get :list_subscribers
      get :messages_report
    end

    resources :messages do
      member do
        post :broadcast
        post :move_up
        post :move_down
        get :responses
      end
      collection do
        get :select_import
        post :import
      end

      resources :response_actions do
        collection do
          get :select_import
          post :import
        end
      end
    end
  end

  post "channels/:channel_id/add_subscriber/:id" => "channels#add_subscriber", :as => "channel_add_subscriber"
  post "channels/:channel_id/remove_subscriber/:id" => "channels#remove_subscriber", :as => "channel_remove_subscriber"

  resources :channel_groups, except: [:index] do
    member do
      get  :messages_report
      get  :clone
      post :copy
      get  :messages_report
    end
  end

  post "channel_groups/:channel_group_id/remove_channel/:id" => "channel_groups#remove_channel", :as => "channel_group_remove_channel"

  resources :users
  resources :subscribers

  resources :subscriber_activities, except: %i(new create destroy)

  resources :downloads, only: [:index]
  resources :service_identifiers, only: [:index]

  match "subscribe/:channel_group_id" => "home#new_web_subscriber", :via => %i(get post)
  get "thank_you" => "home#sign_up_success"
  post "twilio" => "twilio#callback"

  match "help/user_show", via: :all
  match "help/edit_channel", via: :all
  match "help/edit_message", via: :all
  match "help/index_channels", via: :all
  match "help/edit_response_action", via: :all
  match "help/glossary", via: :all
end

app/models/channel_group.rb
# == Schema Information
#
# Table name: channel_groups
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  description        :text
#  user_id            :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  tparty_keyword     :string(255)
#  keyword            :string(255)
#  default_channel_id :integer
#  moderator_emails   :text
#  real_time_update   :boolean
#  deleted_at         :datetime
#  web_signup         :boolean          default(FALSE)
#

class ChannelGroup < ApplicationRecord
  belongs_to :user
  belongs_to :default_channel, class_name: "Channel"

  has_many :channels, before_add: :check_channel_group_credentials
  has_many :subscriber_responses

  validates :name, presence: true, uniqueness: {
    scope: %i(user_id deleted_at),
  }
  validates :keyword, uniqueness: {
    scope: %i(tparty_keyword deleted_at),
    case_sensitive: false,
    allow_blank: true,
  }
  validates :tparty_keyword, presence: true, tparty_keyword: true
  validates :moderator_emails, allow_blank: true, emails: true

  before_create :add_keyword
  before_destroy :remove_keyword
  after_update :update_channel_tparty_keywords

  acts_as_paranoid

  after_initialize do |channel_group|
    if channel_group.new_record?
      begin
        channel_group.tparty_keyword ||= ENV["TPARTY_PRIMARY_KEYWORD"]
      rescue ActiveModel::MissingAttributeError => e
        raise e.message
      end
    end
  end

  def self.find_by_keyword(keyword)
    where("LOWER(keyword) = ?", keyword.downcase).first
  end

  def self.by_keyword(keyword)
    where("LOWER(keyword) = ?", keyword.downcase)
  end

  def self.find_by_tparty_keyword(tparty_keyword)
    where("LOWER(tparty_keyword) = ?", tparty_keyword.downcase).first
  end

  def self.by_tparty_keyword(tparty_keyword)
    where("LOWER(tparty_keyword) = ?", tparty_keyword.downcase)
  end

  def self.identify_command(message_text)
    return :custom if message_text.blank?

    tokens = message_text.split
    return :custom if tokens.length > 1
    return nil if tokens.length < 1

    case tokens[0]
    when /start/i then :start
    when /stop/i then :stop
    else :custom
    end
  end

  def all_channel_subscribers
    channels.includes(:subscribers).map(&:subscribers).flatten
  end

  def process_subscriber_response(subscriber_response)
    case ChannelGroup.identify_command(subscriber_response.content_text)
    when :start
      process_start_command(subscriber_response)
    when :stop
      process_stop_command(subscriber_response)
    when :custom
      process_custom_command(subscriber_response)
    else
      false
    end
  end

  def process_start_command(subscriber_response)
    phone_number = subscriber_response.origin

    return false if !phone_number || phone_number.blank?
    return false unless default_channel
    return true if channels.with_subscriber(phone_number).size > 0

    subscriber = user.subscribers.find_by_phone_number(phone_number)
    unless subscriber
      subscriber = user.subscribers.create!(phone_number: phone_number, name: phone_number)
    end
    default_channel.subscribers.push subscriber
    true
  end

  def process_stop_command(subscriber_response)
    phone_number = subscriber_response.origin
    return false if phone_number.blank?

    found = false
    channels.with_subscriber(phone_number).find_each do |ch|
      found = true
      ch.subscribers.destroy ch.subscribers.find_by_phone_number(phone_number)
    end

    found
  end

  def process_custom_command(subscriber_response)
    return true if process_on_demand_channels(subscriber_response)
    ch = subscriber_response.channel
    ch ? ask_channel_to_process_subscriber_response(ch, subscriber_response) : false
  end

  def process_on_demand_channels(subscriber_response)
    msg = subscriber_response.content_text

    return false if msg.blank?
    tokens = msg.split
    return false unless tokens.length == 1

    channels
      .where(
        "type = :type AND LOWER(one_word) = :one_word_downcase",
        type: "OnDemandMessagesChannel",
        one_word_downcase: tokens[0].downcase,
      )
      .first
      &.process_subscriber_response subscriber_response
  end

  def ask_channel_to_process_subscriber_response(channel, subscriber_response)
    return channel.process_custom_command(subscriber_response)
  end

  def messages_report(options = {})
    col_names = [
      "User Name", "Phone Number", "Channel", "Message", "Sent At",
      "Response", "Received At"
    ]

    CSV.generate(options) do |csv|
      csv << col_names
      subscriber_responses.includes(:subscriber).find_each do |sr|
        record = []
        next if sr.subscriber.blank?
        record << sr.subscriber.name
        record << sr.subscriber.phone_number
        record << "" # channel
        record << "" # message
        record << "" # sent_at
        record << sr.content_text
        record << sr.created_at
        csv << record
      end

      channels.find_each do |ch|
        ch.subscriber_responses.includes(:subscriber, :message).find_each do |sr|
          record = []
          next if sr.subscriber.blank?
          record << sr.subscriber.name
          record << sr.subscriber.phone_number
          record << ch.name
          record << (sr.message.present? ? sr.message.caption : "")
          record << (sr.message.present? ? sr.message.delivery_notices.where(subscriber_id: sr.subscriber.id).first.created_at : "")
          record << sr.content_text
          record << sr.created_at
          csv << record
        end
      end
    end
  end

  private

    def update_channel_tparty_keywords
      channels.each do |channel|
        channel.tparty_keyword = self.tparty_keyword
        channel.save
      end
    end

    def check_channel_group_credentials(channel)
      if channel && channel.class != Hash
        if channels.size > 0 && channel.user_id != channels.first.user_id
          raise ActiveRecord::Rollback, "Channel has to be of same user."
        end

        if channel.channel_group && channel.channel_group != self
          raise ActiveRecord::Rollback, "Channel is already part of another group."
        end
      end
      true
    end

    def add_keyword
      cg = ChannelGroup.find_by_tparty_keyword(tparty_keyword)
      unless cg
        MessagingManagerWorker.perform_async "add_keyword", "keyword" => tparty_keyword
      end
    end

    def remove_keyword
      if tparty_keyword && ChannelGroup.by_tparty_keyword(tparty_keyword).count == 1
        MessagingManagerWorker.perform_async "remove_keyword", "keyword" => tparty_keyword
      end
    end
end

app/controllers/channel_groups_controller.rb
class ChannelGroupsController < ApplicationController
  before_action :load_channel_group, except: %i(create_from_web)
  skip_before_action :load_channel_group, only: %i(new create remove_channel)
  before_action :load_user, only: %i(new create)
  before_action :load_channel, only: %i(remove_channel)

  def show
    if @channel_group
      @channels = @channel_group.channels
        .page(params[:channels_page])
        .per_page(10)
    end
    respond_to do |format|
      format.html
      format.json { render json: @channel_group }
    end
  end

  def new
    @channel_group = @user.channel_groups.new
    respond_to do |format|
      format.html
      format.json { render json: @channel_group }
    end
  end

  def edit; end

  def create
    @channel_group = @user.channel_groups.new(channel_group_params)
    respond_to do |format|
      if @channel_group.save
        format.html do
          redirect_to @channel_group, notice: "Channel group was successfully created."
        end
        format.json { render json: @channel_group, status: :created, location: @channel_group }
      else
        format.html { render action: :new }
        format.json { render json: @channel_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @channel_group.update(channel_group_params)
        format.html do
          redirect_to @channel_group, notice: "Channel group was successfully updated."
        end
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @channel_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @channel_group.destroy
    respond_to do |format|
      format.html { redirect_to user_url(@user) }
      format.json { head :no_content }
    end
  end

  # form for cloning channels that are already existing in the system
  def clone
    clonable_channels = {}
    current_user.channels.active.each do |channel|
      clonable_channels[channel.name] = channel.id
    end
    current_user.channel_groups.each do |potential_group|
      next if potential_group.id == @channel_group.id
      potential_group.channels.active.each do |potential_channel|
        next if potential_channel.user_id != current_user.id
        using_name = "#{potential_group.name}/#{potential_channel.name}"
        clonable_channels[using_name] = potential_channel.id
      end
    end
    @clonable_channels = []
    clonable_channels.keys.sort_by { |x| x[0] }.each do |key|
      @clonable_channels << [key, clonable_channels[key]]
    end
  end

  def copy
    helper = CloneChannel.new(params, @channel_group)
    helper.new_channel
    helper.clone_messages
    redirect_to channel_group_path(@channel_group), notice: "Channel copied. Please review specifically switching channel actions, as guesses are made about which channels you want to switch to."
  rescue => e
    binding.pry
    redirect_to channel_group_path(@channel_group), warn: e.message
  end

  def remove_channel
    already_member = @channel_group.channels.where(id: @channel.id).first
    notice = "Channel not currently part of this group. No changes done."

    if already_member
      @channel_group.channels.delete @channel
      @channel.destroy
      notice = "Channel removed from group."
    end

    respond_to do |format|
      format.html { redirect_to channel_group_path(@channel_group), notice: notice }
      format.json { render json: @channel_group.channels, location: [@channel_group] }
    end
  end

  def messages_report
    respond_to do |format|
      format.csv { send_data @channel_group.messages_report }
    end
  end

  def new_web_subscriber; end

  private

    def channel_group_params
      params.require(:channel_group)
        .permit(
          :description, :name, :keyword, :tparty_keyword, :default_channel_id,
          :moderator_emails, :real_time_update, :web_signup
        )
    end

    def load_user
      authenticate_user!
      @user = current_user
    end

    def load_channel_group
      authenticate_user!
      @user = current_user
      @channel_group = @user.channel_groups.find(params[:id])
      redirect_to root_url, alert: "Access Denied" unless @channel_group
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, alert: "Access Denied"
    end

    def load_channel
      authenticate_user!
      @user = current_user
      @channel_group = @user.channel_groups.find(params[:channel_group_id])
      redirect_to root_url, alert: "Access Denied" unless @channel_group
      @channel = @user.channels.find(params[:id])
      redirect_to root_url, alert: "Access Denied" unless @channel
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, alert: "Access Denied"
    end
end

app/views/channel_groups/_channel_list.html.slim
.panel.panel-default
  .panel-heading
    .row
      .col-md-8
        = "Channels (#{@channels.count})"
      .col-md-4.pull-right.text-right
        = link_to new_channel_path(channel_group_id: @channel_group.to_param), class: "btn btn-primary btn-xs" do
          span.glyphicon.glyphicon-plus
  .panel-body
    - if @channels && @channels.count > 0
      .row
        .col-md-12
          table#channels_table.table.table-striped
            thead: tr
              th Name
              th Keyword
              th.text-center Messages
              th.text-center Subscribers
              th
            tbody
              - if @channels && @channels.count > 0
                - @channels.find_each do |channel|
                  tr id="channel_#{channel.id}"
                    td
                      .name
                        = link_to channel.name, channel_path(channel)
                      .type
                        = channel.type_abbr
                    td.text-center = channel.keyword
                    td.text-center = channel.messages.count
                    td.text-center = channel.subscribers.count
                    td.text-right
                      => link_to "Edit", channel_path(channel), class: "btn btn-xs btn-default"
                      => link_to "Remove",
                                channel_group_remove_channel_path(@channel_group, channel),
                                method: :post,
                                data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
                                class: "btn btn-xs btn-danger"
      .row
        .col-md-12.text-center
          = will_paginate @channels, param_name: "channels_page"
    - else
      .notification-well
        .icon
          span.glpyhicon.glyphicon-plus
        .message
          h4 No Channels Configured
          p Click the plus to add channesl to the system.

app/views/channel_groups/_form.html.slim
= simple_form_for @channel_group, wrapper: :bootstrap_horizontal, html: { class: "form-horizontal" } do |f|
  .row
    .col-md-6
      = f.input :name
      = f.input :description, input_html: { rows: 5 }
      = f.input :keyword, hint: "Used to identify this channel group in user responses"
      = f.input :tparty_keyword, label: "Messaging Service Identifer",
                hint: "Identifies this channel for MO messages"
      = f.association :default_channel, collection: @channel_group.channels
      = f.input :moderator_emails, input_html: { rows: 2 }
      = f.input :real_time_update, wrapper: :inline_checkbox_in_horizontal_form,
                label: "Real time update for moderators", hint: "Hourly (default is daily update by mail)"
      = f.input :web_signup, wrapper: :inline_checkbox_in_horizontal_form,
                label: "Allow subscribers to sign up through the web",
                hint: "Clicking this will give you a web subscription interface that users can use."

  .panel.panel-default
    .panel-body
      => f.button :submit, class: "btn-primary"
      => link_to "Cancel", session[:root_page] || request.referer, class: "btn btn-default"
      - unless @channel_group.new_record?
        => link_to "Delete",
                  channel_group_path(@channel_group),
                  method: :delete,
                  data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
                  class: "btn btn-danger"

app/views/channel_groups/_member_channels.html.slim
h2 Member Channels

table#member_channels_table.table.table-striped
  thead: tr
    th Name
    th Type
    th Actions
  tbody
    - if @member_channels && @member_channels.count > 0
      - @member_channels.find_each do |channel|
        tr id="member_channel_#{channel.id}"
          td= channel.name
          td= channel.type_abbr
          td=> link_to "Remove",
                      channel_group_remove_channel_path(@channel_group, channel),
                      method: :post,
                      class: "btn btn-mini"

- if @member_channels && @member_channels.count > 0
  = will_paginate @member_channels, param_name: "member_channels_page"

app/views/channel_groups/_non_member_channels.html.slim
h2 Non-member Channels

table#non_member_channels_table.table.table-striped
  thead: tr
    th Name
    th Type
    th Actions
  tbody
    - if @non_member_channels && @non_member_channels.count > 0
      - @non_member_channels.find_each do |channel|
        tr id="non_member_channels_#{channel.id}"
          td= channel.name
          td= channel.type_abbr
          td=> link_to "Add to group",
                      channel_group_add_channel_path(@channel_group, channel),
                      method: :post,
                      class: "btn btn-mini"

- if @non_member_channels && @non_member_channels.count > 0
  = will_paginate @non_member_channels, param_name: "non_member_channels_page"

app/views/channel_groups/clone.html.slim
- content_for :title, "#{@channel_group.name} clone channel"

.page-header
  h1 = "Clone existing channel into #{@channel_group.name} Channel Group"

.row
  .col-md-6
    = simple_form_for :request, url: copy_channel_group_path(@channel_group) do |f|
      = f.input :name, as: :string, hint: "Enter the new channel name", placeholder: "Awesome Channel 2"
      = f.input :keyword, as: :string, hint: "Enter a new keyword to select this cahnnel", placeholder: "SHORTSIMPLENAME"
      = f.input :choice, collection: @clonable_channels, hint: "Select a channel to clone. All of its settings and messages will be copied to this channel."
      = f.submit

app/views/channel_groups/edit.html.slim
.page-header: h1 Edit Channel Group

= render partial: "form"
= link_to "Show", @channel_group

app/views/channel_groups/list_channels.html.slim
- content_for :title, "#{@channel_group.name} channel list"

.page-header: h1 #{@channel_group.name} channel list

.row.pagination-centered
  .span6#non_member_channels
    = render partial: "non_member_channels"
  .span5#member_channels
    = render partial: "member_channels"

.form-actions
  => link_to t(".back", default: t("helpers.links.back")),
            channel_group_path(@channel_group),
            class: "btn"

app/views/channel_groups/new.html.slim
- content_for :title, "New Channel Group"
.page-header: h1 New Channel Group
= render partial: "form"

app/views/channel_groups/show.html.slim
- content_for :title, @channel_group.name.titleize

.page-header
  .row
    .col-md-8
      h4
        span.glyphicon.glyphicon-folder-open
        | &nbsp;
        = "#{@channel_group.name} Channel Group"
      p
        = @channel_group.tparty_keyword

.row
  .col-md-12
    dl#channel-group-details.dl-horizontal
      dt: strong Description:
      dd= print_or_dashes @channel_group.description
      dt: strong Default Channel:
      dd= @channel_group.default_channel&.name

.row
  .col-md-12#channel-list
    = render partial: "channel_list"

.panel.panel-default
  .panel-body.text-center
    => link_to "Back", (session[:root_page] || channels_path), class: "btn btn-default"
    => link_to "Edit", edit_channel_group_path(@channel_group), class: "btn btn-default"
    => link_to "Subscriber Activities", subscriber_activities_path(channel_group_id: @channel_group.id), class: "btn btn-default"
    => link_to "Messages Report", messages_report_channel_group_path(@channel_group, format: :csv), class: "btn btn-default"