config/routes.rb
require "sidekiq/web"

Liveinspired::Application.routes.draw do
  root to: "home#index"

  mount Sidekiq::Web => "/sidekiq"
  mount RailsAdmin::Engine => "/admin", :as => "rails_admin"

  devise_for :users

  resources :channels do
    member do
      get :list_subscribers
      get :messages_report
    end

    resources :messages do
      member do
        post :broadcast
        post :move_up
        post :move_down
        get :responses
      end
      collection do
        get :select_import
        post :import
      end

      resources :response_actions do
        collection do
          get :select_import
          post :import
        end
      end
    end
  end

  post "channels/:channel_id/add_subscriber/:id" => "channels#add_subscriber", :as => "channel_add_subscriber"
  post "channels/:channel_id/remove_subscriber/:id" => "channels#remove_subscriber", :as => "channel_remove_subscriber"

  resources :channel_groups, except: [:index] do
    member do
      get  :messages_report
      get  :clone
      post :copy
      get  :messages_report
    end
  end

  post "channel_groups/:channel_group_id/remove_channel/:id" => "channel_groups#remove_channel", :as => "channel_group_remove_channel"

  resources :users
  resources :subscribers

  resources :subscriber_activities, except: %i(new create destroy)

  resources :downloads, only: [:index]
  resources :service_identifiers, only: [:index]

  match "subscribe/:channel_group_id" => "home#new_web_subscriber", :via => %i(get post)
  get "thank_you" => "home#sign_up_success"
  post "twilio" => "twilio#callback"

  match "help/user_show", via: :all
  match "help/edit_channel", via: :all
  match "help/edit_message", via: :all
  match "help/index_channels", via: :all
  match "help/edit_response_action", via: :all
  match "help/glossary", via: :all
end

app/models/subscriber.rb
# == Schema Information
#
# Table name: subscribers
#
#  id                    :integer          not null, primary key
#  name                  :string(255)
#  phone_number          :string(255)
#  remarks               :text
#  last_msg_seq_no       :integer
#  user_id               :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  email                 :string(255)
#  deleted_at            :datetime
#  additional_attributes :text
#  data                  :text
#

require_relative "./mixins/json_serialized_field"

class Subscriber < ApplicationRecord
  include JSONSerializedField

  belongs_to :user

  has_many :subscriptions
  has_many :channels, through: :subscriptions
  has_many :delivery_notices
  has_many :subscriber_responses

  validates :phone_number, presence: true, phone_number: true, uniqueness: {
    scope: %i(user_id deleted_at),
  }
  validates :email, format: { with: /\A.+@.+\z/ }, allow_blank: true

  json_serialize :data

  before_validation :normalize_phone_number

  acts_as_paranoid

  def self.find_by_phone_number(phone_number)
    ref_phone_number = Subscriber.format_phone_number(phone_number)
    where(phone_number: ref_phone_number).first
  end

  def custom_attributes
    @supplied_attributes ||= begin
      attribs = {}
      additional_attributes.to_s.split(";").each do |item|
        key, value = item.to_s.split("=", 2)
        key.downcase!
        attribs[key] = value
      end
      attribs
    end
  end

  def has_custom_attributes?
    custom_attributes && custom_attributes.is_a?(Hash) && custom_attributes.keys.size > 0
  end

  def mark_as_last_message(channel, message)
    data["channels"] = {} if data["channels"].blank?
    data["channels"][channel.id] = {} if data["channels"][channel.id].blank?
    data["channels"][channel.id]["last_sent"] = Time.current
    data["channels"][channel.id]["message_id"] = message.id
  end

  private

    def self.format_phone_number(phone_number)
      return "" if phone_number.blank?

      digits = phone_number.gsub(/\D/, "").split(//)
      case digits.length
      when 10 then "+1#{digits.join}"
      when 11 then "+#{digits.join}"
      end
    end

    def normalize_phone_number
      self.phone_number = Subscriber.format_phone_number(phone_number)
    end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :load_subscriber
  skip_before_action :load_subscriber, only: %i(new create index)
  before_action :load_user, only: %i(new create index)

  def index
    session[:root_page] = subscribers_path
    @subscribers = @user.subscribers

    respond_to do |format|
      format.html
      format.json { render json: @subscribers }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @subscriber }
    end
  end

  def new
    @subscriber = @user.subscribers.new
    respond_to do |format|
      format.html
      format.json { render json: @subscriber }
    end
  end

  def edit; end

  def create
    @subscriber = @user.subscribers.new(subscriber_params)
    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: "Subscriber was successfully created." }
        format.json { render json: @subscriber, status: :created, location: @subscriber }
      else
        format.html { render action: :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: "Subscriber was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_path }
      format.json { head :no_content }
    end
  end

  private

    def subscriber_params
      params.require(:subscriber)
        .permit(:name, :phone_number, :remarks, :email, :additional_attributes)
    end

    def load_user
      authenticate_user!
      @user = current_user
    end

    def load_subscriber
      authenticate_user!
      @user = current_user
      @subscriber = @user.subscribers.find(params[:id])
      redirect_to root_url, alert: "Access Denied" unless @subscriber
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, alert: "Access Denied"
    end
end

app/views/subscribers/_form.html.slim
= simple_form_for [@subscriber], wrapper: :bootstrap_horizontal, html: { class: "form-horizontal" } do |f|
  .row
    .col-md-6
      = f.input :name
      = f.input :phone_number
      = f.input :additional_attributes,
                input_html: { rows: 5 },
                hint: "These can replace placeholders in messages. e.g name=xxx;salutions=Mr;"
      = f.input :remarks, input_html: { rows: 5 }

  .panel.panel-default
    .panel-body
      => f.button :submit, class: "btn-primary"
      => link_to "Cancel", session[:root_page] || request.referer, class: "btn btn-default"
      - unless @subscriber.new_record?
        => link_to t(".destroy", default: t("helpers.links.destroy")),
                  subscriber_path(@subscriber),
                  method: :delete,
                  data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
                  class: "btn btn-danger"

app/views/subscribers/edit.html.slim
- model_class = Subscriber

.page-header: h1
  = t ".title", default: [:"helpers.titles.edit", "Edit %{model}"], model: model_class.model_name.human.titleize

= render partial: "form"

app/views/subscribers/index.html.slim
- model_class = Subscriber

.page-header
  .row
    .col-md-8
      h4 Subscribers
    .col-md-4.text-right.pull-right
      = link_to new_subscriber_path, class: "btn btn-primary btn-xs"
        span.glyphicon.glyphicon-plus

table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:phone_number)
      th= model_class.human_attribute_name(:remarks)
      th= model_class.human_attribute_name(:created_at)
      th
  tbody
    - @subscribers.each do |subscriber|
      tr
        td= link_to subscriber.name, subscriber_path(subscriber)
        td= subscriber.phone_number
        td= subscriber.remarks
        td= subscriber.created_at
        td.text-right
           = link_to t(".edit", default: t("helpers.links.edit")),
                      edit_subscriber_path(subscriber),
                      class: "btn btn-default btn-xs"

.row
  .col-md-12.text-center
  // TODO Should be a pagination here

app/views/subscribers/new.html.slim
- model_class = Subscriber

.page-header: h1
  = t ".title", default: [:"helpers.titles.new", "New %{model}"], model: model_class.model_name.human.titleize

= render partial: "form"

app/views/subscribers/show.html.slim
- model_class = Subscriber

.page-header: h1= @subscriber.name

dl.dl-horizontal
  dt: strong Name:
  dd= print_or_dashes @subscriber.name
  dt: strong Phone number:
  dd= print_or_dashes @subscriber.phone_number
  dt: strong Remarks:
  dd= @subscriber.remarks

.panel.panel-default
  .panel-body
    => link_to "Back", request.referer, class: "btn btn-default"
    => link_to t(".edit", default: t("helpers.links.edit")),
              edit_subscriber_path(@subscriber),
              class: "btn btn-default"
    => link_to t(".destroy", default: t("helpers.links.destroy")),
              subscriber_path(@subscriber),
              method: :delete,
              data: { confirm: t(".confirm", default: t("helpers.links.confirm", default: "Are you sure?")) },
              class: "btn btn-danger"
    => link_to "Subscriber Activities",
              subscriber_activities_path(subscriber_id: @subscriber.id),
              class: "btn btn-default"